"""
Train NAGphormer on UrbanKG Hop2Token tensors.

Expected input is generated by:

    /opt/anaconda3/bin/python src/tokenization/extract_nagphormer_tokens.py
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
import torch.utils.data as Data


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.models import NAGphormer  # noqa: E402


DEFAULT_DATA = PROJECT_ROOT / "output" / "token" / "nagphormer" / "nagphormer_data.pt"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "output" / "token" / "nagphormer"


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)


def accuracy(log_probs: torch.Tensor, labels: torch.Tensor) -> float:
    predictions = log_probs.argmax(dim=1)
    return float((predictions == labels).float().mean().item())


def macro_f1(log_probs: torch.Tensor, labels: torch.Tensor, n_class: int) -> float:
    predictions = log_probs.argmax(dim=1)
    scores = []
    for cls in range(n_class):
        tp = ((predictions == cls) & (labels == cls)).sum().item()
        fp = ((predictions == cls) & (labels != cls)).sum().item()
        fn = ((predictions != cls) & (labels == cls)).sum().item()
        denom = 2 * tp + fp + fn
        if denom > 0:
            scores.append((2 * tp) / denom)
    return float(sum(scores) / len(scores)) if scores else 0.0


def evaluate(model: NAGphormer, loader: Data.DataLoader, device: torch.device, n_class: int) -> dict[str, float]:
    model.eval()
    total_loss = 0.0
    total_count = 0
    all_outputs = []
    all_labels = []
    with torch.no_grad():
        for features, labels in loader:
            features = features.to(device)
            labels = labels.to(device)
            output = model(features)
            loss = F.nll_loss(output, labels, reduction="sum")
            total_loss += float(loss.item())
            total_count += labels.numel()
            all_outputs.append(output.cpu())
            all_labels.append(labels.cpu())

    if not all_outputs:
        return {"loss": 0.0, "accuracy": 0.0, "macro_f1": 0.0}

    outputs = torch.cat(all_outputs, dim=0)
    labels = torch.cat(all_labels, dim=0)
    return {
        "loss": total_loss / max(1, total_count),
        "accuracy": accuracy(outputs, labels),
        "macro_f1": macro_f1(outputs, labels, n_class),
    }


def make_loader(
    hop_tokens: torch.Tensor,
    labels: torch.Tensor,
    indices: torch.Tensor,
    batch_size: int,
    shuffle: bool,
) -> Data.DataLoader:
    valid_indices = indices[labels[indices] >= 0]
    dataset = Data.TensorDataset(hop_tokens[valid_indices], labels[valid_indices])
    return Data.DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train NAGphormer on UrbanKG Hop2Token data.")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--seed", type=int, default=3407)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--epochs", type=int, default=300)
    parser.add_argument("--patience", type=int, default=30)
    parser.add_argument("--peak-lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--n-layers", type=int, default=2)
    parser.add_argument("--n-heads", type=int, default=8)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--attention-dropout", type=float, default=0.1)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    try:
        data = torch.load(args.data, map_location="cpu", weights_only=True)
    except TypeError:
        data = torch.load(args.data, map_location="cpu")
    hop_tokens: torch.Tensor = data["hop_tokens"].float()
    labels: torch.Tensor = data["labels"].long()
    splits: dict[str, torch.Tensor] = data["splits"]

    hops = hop_tokens.shape[1] - 1
    input_dim = hop_tokens.shape[2]
    n_class = int(labels[labels >= 0].max().item()) + 1

    train_loader = make_loader(hop_tokens, labels, splits["train"], args.batch_size, True)
    val_loader = make_loader(hop_tokens, labels, splits["val"], args.batch_size, False)
    test_loader = make_loader(hop_tokens, labels, splits["test"], args.batch_size, False)

    model = NAGphormer(
        hops=hops,
        n_class=n_class,
        input_dim=input_dim,
        n_layers=args.n_layers,
        num_heads=args.n_heads,
        hidden_dim=args.hidden_dim,
        dropout_rate=args.dropout,
        attention_dropout_rate=args.attention_dropout,
    ).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.peak_lr, weight_decay=args.weight_decay)

    print(model)
    print("total params:", sum(p.numel() for p in model.parameters()))
    print(f"device={device} hops={hops} input_dim={input_dim} n_class={n_class}")

    best_state = None
    best_epoch = -1
    best_val = -1.0
    best_val_loss = float("inf")
    bad_epochs = 0
    history = []
    start_time = time.time()

    for epoch in range(args.epochs):
        model.train()
        train_loss_sum = 0.0
        train_count = 0
        train_outputs = []
        train_labels = []

        for features, batch_labels in train_loader:
            features = features.to(device)
            batch_labels = batch_labels.to(device)
            optimizer.zero_grad()
            output = model(features)
            loss = F.nll_loss(output, batch_labels)
            loss.backward()
            optimizer.step()

            train_loss_sum += float(loss.item()) * batch_labels.numel()
            train_count += batch_labels.numel()
            train_outputs.append(output.detach().cpu())
            train_labels.append(batch_labels.detach().cpu())

        train_output = torch.cat(train_outputs, dim=0)
        train_label = torch.cat(train_labels, dim=0)
        train_metrics = {
            "loss": train_loss_sum / max(1, train_count),
            "accuracy": accuracy(train_output, train_label),
            "macro_f1": macro_f1(train_output, train_label, n_class),
        }
        val_metrics = evaluate(model, val_loader, device, n_class)

        row = {
            "epoch": epoch + 1,
            "train": train_metrics,
            "val": val_metrics,
        }
        history.append(row)
        print(
            f"Epoch {epoch + 1:04d} "
            f"loss_train={train_metrics['loss']:.4f} "
            f"acc_train={train_metrics['accuracy']:.4f} "
            f"loss_val={val_metrics['loss']:.4f} "
            f"acc_val={val_metrics['accuracy']:.4f} "
            f"f1_val={val_metrics['macro_f1']:.4f}"
        )

        improved = (
            val_metrics["accuracy"] > best_val
            or (
                abs(val_metrics["accuracy"] - best_val) < 1e-8
                and val_metrics["loss"] < best_val_loss
            )
        )
        if improved:
            best_val = val_metrics["accuracy"]
            best_val_loss = val_metrics["loss"]
            best_epoch = epoch
            best_state = {key: value.detach().cpu().clone() for key, value in model.state_dict().items()}
            bad_epochs = 0
        else:
            bad_epochs += 1

        if bad_epochs >= args.patience:
            print(f"Early stopping at epoch {epoch + 1}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)

    test_metrics = evaluate(model, test_loader, device, n_class)
    print("Optimization Finished!")
    print(f"Train cost: {time.time() - start_time:.4f}s")
    print(f"Best epoch: {best_epoch + 1}")
    print(
        "Test set results: "
        f"loss={test_metrics['loss']:.4f} "
        f"accuracy={test_metrics['accuracy']:.4f} "
        f"macro_f1={test_metrics['macro_f1']:.4f}"
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), args.output_dir / "nagphormer_best_model.pt")
    with (args.output_dir / "train_history.json").open("w", encoding="utf-8") as file:
        json.dump(
            {
                "best_epoch": best_epoch + 1,
                "best_val_accuracy": best_val,
                "test": test_metrics,
                "history": history,
            },
            file,
            ensure_ascii=False,
            indent=2,
        )
        file.write("\n")


if __name__ == "__main__":
    main()
